# Generated by Django 4.0 on 2024-02-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_location_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdetail',
            old_name='description',
            new_name='topic',
        ),
    ]
