# Generated by Django 4.0 on 2024-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_rename_description_locationdetail_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetail',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
